using System.Windows;
using System.Windows.Controls;
using Microsoft.EntityFrameworkCore;
using POS_WPF.Data;
using POS_WPF.Domain.Products;
namespace POS_WPF;
public partial class CategoryManagementWindow : UserControl
{
 private readonly IDbContextFactory<AppDbContext> _dbFactory;private Guid? _selectedId;private List<CategoryRow> _rows=[];
 public CategoryManagementWindow(IDbContextFactory<AppDbContext> dbFactory){InitializeComponent();_dbFactory=dbFactory;Loaded+=async(_,_)=>{await LoadAsync();ClearForm();Status("Ready for a new category.",true);};}
 private async Task LoadAsync(){await using var db=await _dbFactory.CreateDbContextAsync();_rows=await db.Categories.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new CategoryRow(x.Id,x.Name,x.NameArabic,x.ParentCategoryId,x.IsActive)).ToListAsync();CategoriesGrid.ItemsSource=_rows;ParentBox.ItemsSource=_rows.Where(x=>x.Id!=_selectedId).ToList();}
 private void Search_Changed(object sender,TextChangedEventArgs e){var q=SearchBox.Text.Trim();CategoriesGrid.ItemsSource=string.IsNullOrWhiteSpace(q)?_rows:_rows.Where(x=>x.Name.Contains(q,StringComparison.OrdinalIgnoreCase)||(x.NameArabic?.Contains(q,StringComparison.OrdinalIgnoreCase)??false)).ToList();}
 private async void Refresh_Click(object sender,RoutedEventArgs e){await LoadAsync();Status("Categories refreshed.",true);}private void New_Click(object sender,RoutedEventArgs e){ClearForm();Status("Ready for a new category.",true);}
 private void ClearForm(){_selectedId=null;CategoriesGrid.SelectedItem=null;NameBox.Clear();ArabicNameBox.Clear();ParentBox.SelectedValue=null;NameBox.Focus();}
 private void Category_Selected(object sender,SelectionChangedEventArgs e){if(CategoriesGrid.SelectedItem is not CategoryRow row)return;_selectedId=row.Id;NameBox.Text=row.Name;ArabicNameBox.Text=row.NameArabic??string.Empty;ParentBox.SelectedValue=row.ParentCategoryId;Status(row.IsActive?"Edit mode — update fields and save.":"Inactive category.",true);}
 private async void Save_Click(object sender,RoutedEventArgs e){try{if(string.IsNullOrWhiteSpace(NameBox.Text))throw new InvalidOperationException("Category name is required.");await using var db=await _dbFactory.CreateDbContextAsync();Category category;if(_selectedId is null){category=new Category(NameBox.Text.Trim(),string.IsNullOrWhiteSpace(ArabicNameBox.Text)?null:ArabicNameBox.Text.Trim());if(ParentBox.SelectedValue is Guid parent)category.SetParent(parent);db.Categories.Add(category);}else{category=await db.Categories.SingleAsync(x=>x.Id==_selectedId.Value);category.Rename(NameBox.Text.Trim(),string.IsNullOrWhiteSpace(ArabicNameBox.Text)?null:ArabicNameBox.Text.Trim());if(ParentBox.SelectedValue is Guid parent&&parent!=category.Id)category.SetParent(parent);else category.SetParent(null);category.SetActive(true);}await db.SaveChangesAsync();await LoadAsync();ClearForm();Status("Category saved successfully. Form is ready for the next category.",true);}catch(Exception ex){Status(ex.InnerException?.Message??ex.Message,false);}}
 private async void Deactivate_Click(object sender,RoutedEventArgs e){if(_selectedId is not Guid id){Status("Select a category first.",false);return;}try{await using var db=await _dbFactory.CreateDbContextAsync();var category=await db.Categories.SingleAsync(x=>x.Id==id);category.SetActive(false);await db.SaveChangesAsync();await LoadAsync();ClearForm();Status("Category deactivated successfully.",true);}catch(Exception ex){Status(ex.InnerException?.Message??ex.Message,false);}}
 private async void Delete_Click(object sender,RoutedEventArgs e){if(_selectedId is not Guid id){Status("Select a category first.",false);return;}try{await using var db=await _dbFactory.CreateDbContextAsync();var used=await db.Products.AnyAsync(x=>x.CategoryId==id);if(used){var usedCategory=await db.Categories.SingleAsync(x=>x.Id==id);usedCategory.SetActive(false);}else{var category=await db.Categories.SingleAsync(x=>x.Id==id);db.Categories.Remove(category);}await db.SaveChangesAsync();await LoadAsync();ClearForm();Status(used?"Category deactivated because products use it.":"Category deleted successfully.",true);}catch(Exception ex){Status(ex.InnerException?.Message??ex.Message,false);}}
 private void Status(string message,bool success){StatusText.Foreground=success?System.Windows.Media.Brushes.DarkGreen:System.Windows.Media.Brushes.DarkRed;StatusText.Text=success?"✓  "+message:"⚠  "+message;}
 private sealed record CategoryRow(Guid Id,string Name,string? NameArabic,Guid? ParentCategoryId,bool IsActive){public string Status=>IsActive?"Active":"Inactive";}
}