using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using Microsoft.EntityFrameworkCore;
using POS_WPF.Data;
using POS_WPF.Domain.Promotions;
using POS_WPF.Domain.Products;

namespace POS_WPF;

public partial class PromotionsWindow : UserControl
{
    private readonly IDbContextFactory<AppDbContext> _dbFactory; private Guid? _selectedId; private List<PromotionRow> _rows=[];
    public PromotionsWindow(IDbContextFactory<AppDbContext> dbFactory){InitializeComponent();_dbFactory=dbFactory;Loaded+=async(_,_)=>{await LoadProductsAsync();await LoadAsync();NewPromotion();};}
    private async Task LoadProductsAsync(){await using var db=await _dbFactory.CreateDbContextAsync();ProductBox.ItemsSource=await db.Products.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(x=>new ProductOption(x.Id,x.Sku+" — "+x.Name)).ToListAsync();}
    private async void Product_Changed(object sender,SelectionChangedEventArgs e){if(ProductBox.SelectedValue is not Guid productId)return;await using var db=await _dbFactory.CreateDbContextAsync();UnitBox.ItemsSource=await db.ProductUnits.AsNoTracking().Where(x=>x.ProductId==productId&&x.IsActive&&x.CanSell).OrderByDescending(x=>x.IsBaseUnit).ThenBy(x=>x.Name).Select(x=>new UnitOption(x.Id,x.Name+" — "+x.Abbreviation,x.SellingPrice)).ToListAsync();if(UnitBox.Items.Count>0)UnitBox.SelectedIndex=0;}
    private async Task LoadAsync(){await using var db=await _dbFactory.CreateDbContextAsync();_rows=await db.Promotions.AsNoTracking().OrderByDescending(x=>x.CreatedAtUtc).Select(x=>new PromotionRow(x.Id,x.Code,x.Name,x.ProductId,x.Type,x.StartsAtUtc,x.EndsAtUtc,x.IsActive,db.Products.Where(p=>p.Id==x.ProductId).Select(p=>p.Name).FirstOrDefault())).ToListAsync();PromotionsGrid.ItemsSource=_rows;}
    private void Search_Changed(object sender,TextChangedEventArgs e){var q=SearchBox.Text.Trim();PromotionsGrid.ItemsSource=string.IsNullOrWhiteSpace(q)?_rows:_rows.Where(x=>x.Code.Contains(q,StringComparison.OrdinalIgnoreCase)||x.Name.Contains(q,StringComparison.OrdinalIgnoreCase)||(x.ProductName?.Contains(q,StringComparison.OrdinalIgnoreCase)??false)).ToList();}
    private async void Refresh_Click(object sender,RoutedEventArgs e){await LoadProductsAsync();await LoadAsync();Status("Promotions refreshed.",true);}
    private void New_Click(object sender,RoutedEventArgs e)=>NewPromotion();
    private void NewPromotion(){_selectedId=null;PromotionsGrid.SelectedItem=null;CodeBox.Clear();NameBox.Clear();ProductBox.SelectedValue=null;UnitBox.ItemsSource=null;TypeBox.SelectedIndex=0;ValueBox.Clear();MinimumQuantityBox.Text="1";RewardQuantityBox.Text="0";MaxQuantityBox.Clear();StartDateBox.SelectedDate=DateTime.Today;EndDateBox.SelectedDate=null;Status("Ready for a new promotion.",true);CodeBox.Focus();}
    private async void Promotion_Selected(object sender,SelectionChangedEventArgs e){if(PromotionsGrid.SelectedItem is not PromotionRow row)return;try{_selectedId=row.Id;await using var db=await _dbFactory.CreateDbContextAsync();var p=await db.Promotions.AsNoTracking().SingleAsync(x=>x.Id==row.Id);CodeBox.Text=p.Code;NameBox.Text=p.Name;ProductBox.SelectedValue=p.ProductId;TypeBox.SelectedIndex=p.Type switch{PromotionType.Percentage=>0,PromotionType.FixedAmount=>1,PromotionType.BuyXGetY=>2,PromotionType.QuantityDiscount=>3,_=>1};ValueBox.Text=p.Value.ToString(CultureInfo.CurrentCulture);MinimumQuantityBox.Text=p.MinimumQuantity.ToString(CultureInfo.CurrentCulture);RewardQuantityBox.Text=p.RewardQuantity.ToString(CultureInfo.CurrentCulture);MaxQuantityBox.Text=p.MaxQuantity?.ToString(CultureInfo.CurrentCulture)??string.Empty;StartDateBox.SelectedDate=p.StartsAtUtc.ToLocalTime().Date;EndDateBox.SelectedDate=p.EndsAtUtc?.ToLocalTime().Date;await Product_Changed(this,new SelectionChangedEventArgs(Selector.SelectionChangedEvent,null));UnitBox.SelectedValue=p.UnitId;Status(p.IsActive?"Edit mode — update and save.":"Inactive promotion.",true);}catch(Exception ex){Status(ex.Message,false);}}
    private async void Save_Click(object sender,RoutedEventArgs e){try{if(string.IsNullOrWhiteSpace(CodeBox.Text)||string.IsNullOrWhiteSpace(NameBox.Text))throw new InvalidOperationException("Promotion code and name are required.");if(ProductBox.SelectedValue is not Guid productId)throw new InvalidOperationException("Select a product.");if(UnitBox.SelectedValue is not Guid unitId)throw new InvalidOperationException("Select a sellable unit.");if(!decimal.TryParse(ValueBox.Text,NumberStyles.Number,CultureInfo.CurrentCulture,out var value)||value<=0)throw new InvalidOperationException("Value must be greater than zero.");if(!decimal.TryParse(MinimumQuantityBox.Text,NumberStyles.Number,CultureInfo.CurrentCulture,out var minQty)||minQty<=0)throw new InvalidOperationException("Minimum quantity must be greater than zero.");if(!decimal.TryParse(RewardQuantityBox.Text,NumberStyles.Number,CultureInfo.CurrentCulture,out var rewardQty)||rewardQty<0)throw new InvalidOperationException("Reward quantity cannot be negative.");decimal? maxQty=null;if(!string.IsNullOrWhiteSpace(MaxQuantityBox.Text)){if(!decimal.TryParse(MaxQuantityBox.Text,NumberStyles.Number,CultureInfo.CurrentCulture,out var parsed)||parsed<=0)throw new InvalidOperationException("Maximum promotion quantity must be greater than zero.");maxQty=parsed;}var type=TypeBox.SelectedIndex switch{0=>PromotionType.Percentage,1=>PromotionType.FixedAmount,2=>PromotionType.BuyXGetY,_=>PromotionType.QuantityDiscount};if(type==PromotionType.Percentage&&value>100)throw new InvalidOperationException("Percentage discount cannot exceed 100%.");if(type==PromotionType.BuyXGetY&&rewardQty<=0)throw new InvalidOperationException("Buy X Get Y requires a reward quantity.");if(type==PromotionType.QuantityDiscount&&value<=0)throw new InvalidOperationException("Quantity deal total price must be greater than zero.");var start=(StartDateBox.SelectedDate??DateTime.Today).Date.ToUniversalTime();var end=EndDateBox.SelectedDate?.Date.ToUniversalTime().AddDays(1).AddTicks(-1);if(end.HasValue&&end<start)throw new InvalidOperationException("End date must be after start date.");await using var db=await _dbFactory.CreateDbContextAsync();Promotion p;if(_selectedId is null){p=new Promotion(CodeBox.Text.Trim(),NameBox.Text.Trim(),type,start,end);db.Promotions.Add(p);}else{p=await db.Promotions.SingleAsync(x=>x.Id==_selectedId.Value);}p.Code=CodeBox.Text.Trim();p.Name=NameBox.Text.Trim();p.Type=type;p.ProductId=productId;p.UnitId=unitId;p.Value=value;p.MinimumQuantity=minQty;p.RewardQuantity=rewardQty;p.MaxQuantity=maxQty;p.StartsAtUtc=start;p.EndsAtUtc=end;p.IsActive=true;await db.SaveChangesAsync();await LoadAsync();Status("Promotion saved successfully.",true);NewPromotion();}catch(Exception ex){Status(ex.InnerException?.Message??ex.Message,false);}}
    private async void Deactivate_Click(object sender,RoutedEventArgs e){if(_selectedId is not Guid id){Status("Select a promotion first.",false);return;}try{await using var db=await _dbFactory.CreateDbContextAsync();var p=await db.Promotions.SingleAsync(x=>x.Id==id);p.IsActive=false;await db.SaveChangesAsync();await LoadAsync();Status("Promotion deactivated successfully.",true);NewPromotion();}catch(Exception ex){Status(ex.InnerException?.Message??ex.Message,false);}}
    private void Status(string message,bool success){StatusText.Foreground=success?System.Windows.Media.Brushes.DarkGreen:System.Windows.Media.Brushes.DarkRed;StatusText.Text=success?"✓  "+message:"⚠  "+message;}
    private sealed record ProductOption(Guid Id,string Display);private sealed record UnitOption(Guid Id,string Display,decimal Price);private sealed record PromotionRow(Guid Id,string Code,string Name,Guid? ProductId,PromotionType Type,DateTime StartsAtUtc,DateTime? EndsAtUtc,bool IsActive,string? ProductName){public string TypeText=>Type switch{PromotionType.Percentage=>"Percentage",PromotionType.FixedAmount=>"Fixed amount",PromotionType.BuyXGetY=>"Buy X Get Y",PromotionType.QuantityDiscount=>"Quantity deal",_=>Type.ToString()};public string Period=>$"{StartsAtUtc.ToLocalTime():yyyy-MM-dd} → {(EndsAtUtc?.ToLocalTime().ToString("yyyy-MM-dd")??"No end")}";public string Status=>IsActive?"Active":"Inactive";}
}
